name: empe
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - numpy=1.26.4
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - rdkit
  - openbabel
  - pytorch
  - tqdm
  - pip
  - pip:
      - selfies
      - py3Dmol
      - chemprop==2.1.0
      - pytorch-lightning
      - lightning
