name: empenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - rdkit
  - openbabel
  - pytorch
  - tqdm
  - pip
  - pip:
      - selfies
      - py3Dmol
      - chemprop
      - pytorch-lightning
